#!/bin/csh
#PBS -l mppwidth=24
#PBS -l walltime=5:00
#PBS -q debug
#PBS -j oe
cd $PBS_O_WORKDIR
module load python
module load mpi4py

for solverSeed in 57 26 38 12 97
do
	aprun -n 24 python ParallelKsatApplication.py --generator "MpiKsatProblem.RandomMpiKsatGenerator(10, 10000, 10000)" --solver "LllKsatSolver.LllKsatSolver(IndependentSetFinder.SimpleChungIndependentSetFinder())" --problemSeed 3 --solverSeed $solverSeed
done
